apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/testapp:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: testapp-config
            - secretRef:
                name: testapp-secrets
