apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp-container
          image: "${REGISTRY_SOURCE}/${AZURE_USERNAME}/${REGISTRY_IMAGE}:${IMAGE_TAG}"  # Placeholder for dynamic update
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
