apiVersion: v1
kind: Secret
metadata:
  name: testapp-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "${DATABASE_USERNAME}" # Base64-encoded username
  SPRING_DATASOURCE_PASSWORD: "${DATABASE_PASSWORD}" # Base64-encoded password
