name: Build, push and deploy container app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE: '${{ vars.REGISTRY_SOURCE }}/${{ vars.AZURE_USERNAME }}/${{ vars.REGISTRY_IMAGE }}'

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY_SOURCE }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}


      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: '${{env.DOCKER_IMAGE}}:${{ github.run_number }}, ${{env.DOCKER_IMAGE}}:latest'
          file: Dockerfile